# Site wide configuration

title: "行到水窮處 坐看雲起時"
locale: zh_TW
description: Describe your website here.
logo: 
search: true
url: 
timezone: Asia/Taipei

# Jekyll configuration

permalink:   /:year/:month/:day/:title
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

excerpt_separator: "<!-- more -->"

# Site owner
owner:
  name: Aaron Chiang
  avatar: bio-photo.jpg
  email: aaron.chiang.tw@gmail.com
  disqus-shortname: aaronchiang
  twitter: aaronchiang
  facebook: aaron.chiang.tw
  github: aaronchiang
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: aaronchiangtw
  flickr: aaronchiang
  tumblr: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify: